//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.status = "incomplete";
            this.details = "No details available";
        }
    
        public int id { get; set; }
        public int restaurantId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string maxTime { get; set; }
        public string status { get; set; }
        public string details { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
